[project]
name = 'Tokenized-Decentralized-Fitness-Coaching-Networks'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.nutrition-guidance]
path = 'contracts/nutrition-guidance.clar'
clarity_version = 2
epoch = 2.5

[contracts.progress-monitoring]
path = 'contracts/progress-monitoring.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
